added pass/fail logs

diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -18,4 +18,10 @@ jobs:
         gem install bundler
         bundle install --jobs 4 --retry 3
         bundle exec rake install
-        if [[ $($ echo "foobar") == "foobar" ]]; then exit 0; else exit 1; fi
+        if [[ $($ echo "foobar") == "foobar" ]]; then 
+          echo "Test passed –– exiting with code 0";
+          exit 0; 
+        else 
+          echo "Test failed –– exiting with code 1";
+          exit 1; 
+        fi
